language: node_js
node_js: 8
services:
  - docker
  - redis-server
install:
  - npm install
env:
  - DATABROKER_REDIS_ADDRESS=localhost
script:
  - docker build -t ${TRAVIS_REPO_SLUG} .
  - docker network create dojot-net
  - docker run --rm -d --network dojot-net --name zookeeper zookeeper:3.4
  - docker run --rm -e ZOOKEEPER_IP=localhost -e KAFKA_NUM_PARTITIONS=10 -d --network dojot-net --name kafka ches/kafka:0.10.1.1
  - npm run-script build
  - npm run-script build-tests
  - ./tests/start-test.sh
after_success:
  - travis/publish.sh
  - travis/deploy-gh-pages.sh
