FROM node:8

WORKDIR /opt/data-notifier
EXPOSE 80
CMD ["npm", "run", "notification", "--", "-t", "device-notification", "-k", "kafka:9092", "--deviceManager", "http://device-manager:5000"]

COPY package.json .
COPY package-lock.json .
RUN npm install

COPY . .
RUN npm run-script build

